apiVersion: apps/v1
kind: Deployment
metadata:
  name: luketest-operaotr
spec:
  replicas: 1
  selector:
    matchLabels:
      name: luketest-operaotr
  template:
    metadata:
      labels:
        name: luketest-operaotr
    spec:
      serviceAccountName: luketest-operaotr
      containers:
        - name: luketest-operaotr
          # Replace this with the built image name
          image: ccr.ccs.tencentyun.com/lukexwang/luketest-operator:latest 
          command:
          - luketest-operaotr
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "luketest-operaotr"
