kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: luketest-operaotr
subjects:
- kind: ServiceAccount
  name: luketest-operaotr
roleRef:
  kind: Role
  name: luketest-operaotr
  apiGroup: rbac.authorization.k8s.io
